In [1]:
import pandas as pd
from pathlib import Path

In [2]:
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data"
FILE_NAME = "../data/supermag_electrojet_upper_and_lower_index_1995T2009.pkl"
FILE_PATH = DATA_DIR / FILE_NAME

In [3]:
df = pd.read_pickle(FILE_PATH)

In [4]:
df.head()

                    Date_UTC  SML
14201280 1995-01-01 00:00:00  -17
14201281 1995-01-01 00:01:00  -17
14201282 1995-01-01 00:02:00  -19
14201283 1995-01-01 00:03:00  -22
14201284 1995-01-01 00:04:00  -28

In [5]:
from config import SUPERMAG_ELECTROJET_LOWER_INDEX_FILL_VALUE
import numpy as np

df["SML"] = df["SML"].replace(SUPERMAG_ELECTROJET_LOWER_INDEX_FILL_VALUE, np.nan)

In [6]:
df.head()

                    Date_UTC  SML
14201280 1995-01-01 00:00:00  -17
14201281 1995-01-01 00:01:00  -17
14201282 1995-01-01 00:02:00  -19
14201283 1995-01-01 00:03:00  -22
14201284 1995-01-01 00:04:00  -28